### PR TITLE
Optional response type when 204 response exists

### LINKED ISSUE #1606: Optional response type when 204 response exists
Hi there,

we have the case where an endpoint can return a 200 status code with a body or a 204 (obviously) without one. Therefore, the return type should be optional (i.e. `CancelablePromise<MyType?>` instead of `CancelablePromise<MyType>`). Thus it is clearer that also undefined values might be returned.

### PR DESCRIPTION
**Pull request by mrlubos**
Fixes #1606

### CODE REVIEW

**Comment by mrlubos** [comment]
Hi @ferdikoomen, I'm not sure how reviews work here, but would love to get a feedback on this and ideally get it merged, too!

**Comment by mrlubos** [comment]
Hi @ferdikoomen, did you have time to look at this issue?

**Comment by Marshal27** [comment]
This honestly would not be necessary if the underlying `ApiResult` was returned for all `Http` clients, and not just the `Angular` `Http` client. 

This response shape would give any consuming application access to the response status code, and the consuming app could then vend any return shape it wants for a `204` no content. 

It is not necessary to bake something like this in to the repo, if, the response shape would become more reflective of a native `Response` shape vs just returning the response body.

**Comment by mrlubos** [comment]
Possible next iteration @Marshal27? If this gets merged I could have a look into it

**Comment by Marshal27** [comment]
@mrlubos I am still new to this repo, and evaluating it as a possible option for our company. You can review some of my comments on this topic in #1342. I would be more than happy to contribute to this repo, however, there seems to be a bit of a backlog on PR(s) and possibly this project is becoming unmaintained.  

If you wanted to explore this in your own fork, simply modify the `request.hbs` file foryour respective `http` client in the following directory.

`src/templates/core`

For example, I am currently using the default `fetch` client and would modify the `resolve` in `src/templates/core/fetch/request.hbs` from this:

```ts
if (!onCancel.isCancelled) {
		const response = await sendRequest(config, options, url, body, formData, headers, onCancel);
		const responseBody = await getResponseBody(response);
		const responseHeader = getResponseHeader(response, options.responseHeader);

		const result: ApiResult = {
			url,
			ok: response.ok,
			status: response.status,
			statusText: response.statusText,
			body: responseHeader ?? responseBody,
		};

		catchErrorCodes(options, result);

		resolve(result.body);
	}
```

to this:

```ts
if (!onCancel.isCancelled) {
		const response = await sendRequest(config, options, url, body, formData, headers, onCancel);
		const responseBody = await getResponseBody(response);
		const responseHeader = getResponseHeader(response, options.responseHeader);

		const result: ApiResult = {
			url,
			ok: response.ok,
			status: response.status,
			statusText: response.statusText,
			body: responseHeader ?? responseBody,
		};

		catchErrorCodes(options, result);

		resolve(result);
	}
```

If you wanted to surface the underlying `Response` from the prototype, then you could change the `resolve` to this:

```ts
if (!onCancel.isCancelled) {
		const response = await sendRequest(config, options, url, body, formData, headers, onCancel);

		resolve(response );
	}
```

**Comment by mrlubos** [comment]
Hey @danilofuchs, I've decided to merge this in our [fork](https://github.com/nicolas-chaulet/openapi-typescript-codegen), you might find it useful too

**Pull request closed without merging**
