### PR TITLE
GH-633: Fix --useUnionTypes

### LINKED ISSUE #633: --useUnionTypes still creates enums for definitions being an enum
Given an API-Spec with the following definitions in yaml-format

```
definitions:
  Status:
    type: "string"
    description: "pet status in the store"
    enum:
      - "available"
      - "pending"
      - "sold"
  SomeObjectWhereUnionTypeWorks:
    type: object
    description: Status of the building part
    properties:
      status:
        type: "string"
        description: "pet status in the store"
        enum:
          - "available"
          - "pending"
          - "sold"

  SomeOtherObjectWhereUnionTypeFails:
    type: object
    description: Status of the building part
    properties:
      status:
        $ref: "#/definitions/Status"
```

When I generate the typescript objects using
`openapi --useUnionTypes --input ./swagger.yaml --output ./dist`

Then, I get
```
/* SomeObjectWhereUnionTypeWorks.ts */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * Status of the building part
 */
export type SomeObjectWhereUnionTypeWorks = {
    /**
     * pet status in the store
     */
    status?: 'available' | 'pending' | 'sold';
}


/* SomeOtherObjectWhereUnionTypeFails.ts */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { Status } from './Status';

/**
 * Status of the building part
 */
export type SomeOtherObjectWhereUnionTypeFails = {
    status?: Status;
}


/* Status.ts */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * pet status in the store
 */
export enum Status {
    AVAILABLE = 'available',
    PENDING = 'pending',
    SOLD = 'sold',
}
````

I would expect that even Status.ts itself exports a type consisting of an union type instead of an enum.

### PR DESCRIPTION
**Pull request by dbo**
fixes #633 and #634

### CODE REVIEW

**Comment by dbo** [comment]
@ferdikoomen what can I do to drive this further?

**Comment by mfeltscher** [comment]
Stumbled upon the exact same issue - would love to see this change make it into a future release!

**Comment by dbo** [comment]
@ferdikoomen Is this project still open for pull requests? I just see bot commits.

**Comment by joshtronic** [comment]
*bump*

**Pull request merged**
