### PR TITLE
Fixed issue 2052

### PR DESCRIPTION
**Pull request by tajnymag**
Both of these had to be made together to pass our tests
1. always pass absolute url to json-schema-ref-parser
2. update json-schema-ref-parser to v11.1.0

Should fix: https://github.com/ferdikoomen/openapi-typescript-codegen/issues/2052

### CODE REVIEW

**Comment by tajnymag** [comment]
Tests do pass, however, Circle CI workflow should probably be updated to run tests on multiple platforms, not just linux

**Comment by mrlubos** [comment]
Thanks! For anyone looking to try this out, we've merged this pull request in [our fork](https://github.com/nicolas-chaulet/openapi-typescript-codegen), would love your feedback!

**Comment by crashkonijn** [comment]
Having exactly this issue, hopefully this can be merged soon!

**Comment by tajnymag** [comment]
> Having exactly this issue, hopefully this can be merged soon!

Use the fork above in the mean time. It has multiple issues already fixed and some extra features.

**Comment by evgarthub** [comment]
Can confirm it works on Windows.

**Pull request merged**
