### PR TITLE
propertyRequired with definition.required === true

### PR DESCRIPTION
**Pull request by ismail-codar**

### CODE REVIEW

**Comment by ferdikoomen** [comment]
Hey Ismail, let me check why the build failed.

**Comment by ferdikoomen** [comment]
According to the spec required is an array of props, rather then a boolean i believe

**Comment by ferdikoomen** [comment]
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schemaObject

**Comment by ismail-codar** [comment]
My schema object like this.
```json
"schemas": {
      "ErrorResponse": {
        "properties": {
          "type": {
            "type": "string",
            "required": true
```
It looks out of the spec.  I need to contact the API provider

**Pull request closed without merging**
